[project]
name = "my-fastapi-app"
version = "0.1.0"
description = "FastAPI backend on Vercel"
requires-python = ">=3.9"
dependencies = [
    "fastapi",
    "uvicorn",
#    "transformers",
#    "torch",
    "mangum"
]

[project.scripts]
# 기존에 작성하셨던 스크립트 내용이 있다면 이 아래에 유지하세요.
app = "backend.main:app"